### ISSUE TITLE
Current release with docker does not result in a working node server on port 3000

### ISSUE THREAD

**Issue by veixus** [vitorbaptista/shellshare#70]
I have written a little script to setup shellshare server from scratch. It pulls from the Github repo and after that builds the containers. Currently something seems missing and the node container does not start. Im running fresh ubuntu 22.04 LTS but this shouldnt matter.

cd /opt/ && git clone https://github.com/vitorbaptista/shellshare.git
'cd /opt/shellshare && docker-compose up --build

this starts the mongodb but for node server, it gives output "shellshare_node_1 exited with code 0"

Before this, the result was 2 containers and node server listening on port 3000

Possible fix:
add missing line into docker-compose.yml 
"command: "npm start""

Something is not automatically starting, so adding "npm start" seemed to start a service on port 3000
This might not be the right place for this, but seems that it fixed the problem 

```
version: '3'
services:
  mongo:
    image: mongo
    expose:
      - "27017"
  node:
    build: .
    command: "npm start"
    ports:
      - "3000:3000"
    working_dir: /shellshare
    environment:
      - MONGO_URL=mongodb://mongo:27017/shellshare
      - NODE_ENV=production
      # - HOST=
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5m30s
      timeout: 3s
      retries: 3
```
